apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: otel-demo
spec:
  template:
    metadata:
      labels:
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.34.0