apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: otel-demo
  name: my-otel-demo-emailservice  
spec:
  template:
    metadata:
      labels:
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/python-lib.version: v2.6.0