name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  kustomize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: '4.5.5'

    - name: Build kustomization for adservice
      run: kustomize build overlays/adservice -o kustomized-adservice.yaml

    - name: Build kustomization for emailservice
      run: kustomize build overlays/emailservice -o kustomized-emailservice.yaml      

    - name: Upload kustomized-adservice.yaml as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: kustomized-adservice.yaml
        path: kustomized-adservice.yaml

    - name: Upload kustomized-emailservice.yaml as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: kustomized-emailservice.yaml
        path: kustomized-emailservice.yaml        
