name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  kustomize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: '4.5.5'

    - name: Build kustomization
      run: kustomize build overlays/enhanced -o kustomized.yaml

    - name: Upload kustomized.yaml as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: kustomized.yaml
        path: kustomized.yaml
